version:  "2"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
        image: php:7.2-apache
        ports:
          - "8080:80"
        depends_on:
          - mysql
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: example