version:  "2"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
        image: php
        ports:
          - "8080:80"
        depends_on:
          - mysql
    mysql:
        image: mysql